### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by SihamSharif** [mosessoh/CNN-LSTM-Caption-Generator#10]
Hi,
I am facing 

**(tensorflow) [user@hostname CNN-LSTM-Caption-Generator]$ python3.4 caption_image.py -i images/pizza.jpg

  File "caption_image.py", line 25
    print '-'*20
            ^
SyntaxError: Missing parentheses in call to 'print'**

this error.

I am using conda in oracle linux 6.9.

Can you suggest what I am doing wrong?

**Comment by mosessoh** [comment]
You’re using python3 which uses the print statement as print(s) not print s.
