### ISSUE TITLE
connectivity issue

### ISSUE THREAD

**Issue by Sorna210** [mosessoh/CNN-LSTM-Caption-Generator#11]
The connection is refused in download.sh.Can someone provide the new connection?

**Comment by mosessoh** [comment]
Please see my response in #12 . I've created a new download.sh script that should fix the issues you're facing. You should now be able to use the new download.sh script by cloning/pulling the repo. If you're still interested in the project, do let me know if you're facing any issues and I will be happy to try and help.

**Comment by Sorna210** [comment]
Thank you so much sir :)

**Comment by Sorna210** [comment]
Hai sir.When I am running the captions image file I am getting an error
like this.How do I resolve it?
