### ISSUE TITLE
The link in the download.sh can not be accessed

### ISSUE THREAD

**Issue by jiazhaojun** [mosessoh/CNN-LSTM-Caption-Generator#12]
Hello, I am a senior student, thank you for providing this model, I need to study this model in order to do my graduation project. But download.sh does not work, I use google to visit inside the link, return 404. So can you provide the .pkl file for this model, thanks

**Comment by mosessoh** [comment]
Hi! I apologize for the issues that you've been facing - my google drive folder got moved. I've now uploaded **all** models and relevant files to a public S3 bucket. **I've modified the download.sh script to point to this bucket so you will need to pull/clone this.**

This means that everyone should now be able to access and use them for your research. Do give it a try, and let me know if you run into any further issues. Thank you for your interest in my project!

**Comment by SeekPoint** [comment]
https://googledrive.com/host/0B8-CPllE3RJqaHlRTWxxSTI3cW8/index2token.pkl

404

**Comment by mosessoh** [comment]
Can you try it now and let me know if it works?

**Comment by SeekPoint** [comment]
quote:

The requested URL /host/0B8-CPllE3RJqaHlRTWxxSTI3cW8/index2token.pkl was not found on this server. That’s all we know.

**Comment by mosessoh** [comment]
Have you pulled the latest version of the repo? That isn’t the right URL - it has been updated.

**Comment by jiazhaojun** [comment]
Hello, thanks for your reply, I have received your email, and now I have downloaded the required files and are working on it. Sincerely thank you for your help and your work, thanks.



------------------ 原始邮件 ------------------
发件人: "Moses Soh";<notifications@github.com>;
发送时间: 2018年1月17日(星期三) 晚上8:13
收件人: "mosessoh/CNN-LSTM-Caption-Generator"<CNN-LSTM-Caption-Generator@noreply.github.com>;
抄送: "贾兆军"<844819903@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [mosessoh/CNN-LSTM-Caption-Generator] The link in the download.shcan not be accessed (#12)




Hi! I apologize for the issues that you've been facing - my google drive folder got moved. I've now uploaded all models and relevant files to a public S3 bucket. I've modified the download.sh script to point to this bucket so you will need to pull/clone this.
 
This means that everyone should now be able to access and use them for your research. Do give it a try, and let me know if you run into any further issues. Thank you for your interest in my project!

**Comment by SeekPoint** [comment]
it works now

**Comment by mosessoh** [comment]
Great! Will close this now then.
