### ISSUE TITLE
Model building environment

### ISSUE THREAD

**Issue by jiazhaojun** [mosessoh/CNN-LSTM-Caption-Generator#13]
hi, because this model is implemented in python2, but the tensorflow installed on windows can only be based on python3.5, so the installation of this model can only be in linux?

**Comment by mosessoh** [comment]
Yes I did train this on linux. It’s getting easier to run linux alongside or with windows though. You can give this a try : https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by jiazhaojun** [comment]
OK, I'll try, thanks




------------------ 原始邮件 ------------------
发件人: "Moses Soh";<notifications@github.com>;
发送时间: 2018年1月20日(星期六) 中午1:31
收件人: "mosessoh/CNN-LSTM-Caption-Generator"<CNN-LSTM-Caption-Generator@noreply.github.com>;
抄送: "贾兆军"<844819903@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [mosessoh/CNN-LSTM-Caption-Generator] Model building environment(#13)




Closed #13.
