### ISSUE TITLE
a cuda runtime call was likely performed without using a streamExecutor context

### ISSUE THREAD

**Issue by zack6514** [mosessoh/CNN-LSTM-Caption-Generator#2]
Hey, when I use your demo,  and run: python caption -i images/pizza.jpg, But get the problem:  "a cuda runtime call was likely performed without using a streamExecutor context" which caused by the code of "with tf.Session as session", I know it because the file use caffe to extract cnn features and causes the cuda  conflicting with tensorflow ,  what can I do?

**Comment by mosessoh** [comment]
i've only set up the demo to work in CPU mode at the moment. the tensorflow training of the model is the only part that is set up for GPU as that takes a lot of time.

this problem has been documented as a tensorflow / caffe conflict [here](https://github.com/tensorflow/tensorflow/issues/916). one solution (which i used) is to disable the GPU functionality for caffe, and only allow tensorflow to use the GPU. i'll close this issue as it's not a problem with the demo script.

**Comment by zack6514** [comment]
I know it is not the problem with the demo script. But the script has setted the caffe.set_mode_cpu(),    it cannot solve this problem,  could you  give me why?
