### ISSUE TITLE
Unable to download model-37 file

### ISSUE THREAD

**Issue by nemare** [mosessoh/CNN-LSTM-Caption-Generator#4]
Hello , I got a problem like this when I ran the project:

tensorflow/core/util/tensor_slice_reader.cc:93] Could not open best_model/model-37: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

and I tried to download from google drive , it turned out that 404 error.

**Comment by mosessoh** [comment]
@nemare, you have to run the download.sh script, not visit the links. I've tried running the download.sh script again and it works. I'm closing this issue.

**Comment by mosessoh** [comment]
@nemare , i've reuploaded the best model following other issues raised. sorry - please try downloading it again and let me know if there are any issues.

**Comment by nemare** [comment]
Thank you ! It works !

**Comment by Venkatesh-Murthy** [comment]
Hey, I tried downloading it, but I am getting the above mentioned 404 Error. Can you please reupload the model?

**Comment by wuzhengxuan** [comment]
Hey, I tried downloading it, but I am getting the above mentioned 404 Error. Can you please reupload the model?

**Comment by lcwbupt** [comment]
Hey, I tried downloading it, but I am getting the above mentioned 404 Error. Can you please reupload the model?
