### ISSUE TITLE
' failed: Connection refused' when run ' bash download.sh '

### ISSUE THREAD

**Issue by SeekPoint** [mosessoh/CNN-LSTM-Caption-Generator#7]
rzai@rzai00:~/prj/CNN-LSTM-Caption-Generator$ bash download.sh 
--2016-12-20 10:33:35--  https://googledrive.com/host/0B8-CPllE3RJqaHlRTWxxSTI3cW8/index2token.pkl
Resolving googledrive.com (googledrive.com)... 172.217.24.1, 2404:6800:4008:803::2001
Connecting to googledrive.com (googledrive.com)|172.217.24.1|:443... failed: Connection refused.
Connecting to googledrive.com (googledrive.com)|2404:6800:4008:803::2001|:443... failed: Network is unreachable.
--2016-12-20 10:34:38--  https://googledrive.com/host/0B8-CPllE3RJqaHlRTWxxSTI3cW8/preprocessed_train_captions.pkl
Resolving googledrive.com (googledrive.com)... 216.58.200.225, 2404:6800:4008:803::2001
Connecting to googledrive.com (googledrive.com)|216.58.200.225|:443... failed: Connection refused.
Connecting to googledrive.com (googledrive.com)|2404:6800:4008:803::2001|:443... failed: Network is unreachable.
--2016-12-20 10:35:41--  https://googledrive.com/host/0B8-CPllE3RJqaHlRTWxxSTI3cW8/train_image_id2feature.pkl
Resolving googledrive.com (googledrive.com)... 216.58.200.225, 2404:6800:4008:803::2001
Connecting to googledrive.com (googledrive.com)|216.58.200.225|:443... failed: Connection refused.
Connecting to googledrive.com (googledrive.com)|2404:6800:4008:803::2001|:443... failed: Network is unreachable.
--2016-12-20 10:36:44--  https://googledrive.com/host/0B8-CPllE3RJqaHlRTWxxSTI3cW8/val_image_id2feature.pkl
Resolving googledrive.com (googledrive.com)... 216.58.200.225, 2404:6800:4008:803::2001
Connecting to googledrive.com (googledrive.com)|216.58.200.225|:443... failed: Connection refused.
Connecting to googledrive.com (googledrive.com)|2404:6800:4008:803::2001|:443... failed: Network is unreachable.
--2016-12-20 10:37:47--  https://googledrive.com/host/0B8-CPllE3RJqaHlRTWxxSTI3cW8/checkpoint
Resolving googledrive.com (googledrive.com)... 216.58.200.225, 2404:6800:4008:803::2001
Connecting to googledrive.com (googledrive.com)|216.58.200.225|:443... failed: Connection refused.
Connecting to googledrive.com (googledrive.com)|2404:6800:4008:803::2001|:443... failed: Network is unreachable.
--2016-12-20 10:38:50--  https://googledrive.com/host/0B8-CPllE3RJqaHlRTWxxSTI3cW8/model-37
Resolving googledrive.com (googledrive.com)... 216.58.200.225, 2404:6800:4008:803::2001
Connecting to googledrive.com (googledrive.com)|216.58.200.225|:443... failed: Connection refused.
Connecting to googledrive.com (googledrive.com)|2404:6800:4008:803::2001|:443... failed: Network is unreachable.
--2016-12-20 10:39:52--  https://googledrive.com/host/0B8-CPllE3RJqaHlRTWxxSTI3cW8/model-37.meta
Resolving googledrive.com (googledrive.com)... 172.217.24.1, 2404:6800:4008:803::2001
Connecting to googledrive.com (googledrive.com)|172.217.24.1|:443... failed: Connection refused.
Connecting to googledrive.com (googledrive.com)|2404:6800:4008:803::2001|:443... failed: Network is unreachable.
rzai@rzai00:~/prj/CNN-LSTM-Caption-Generator$

**Comment by mosessoh** [comment]
Please see my response in #12 . I've created a new download.sh script that should fix the issues you're facing. You should now be able to use the new download.sh script by cloning/pulling the repo. If you're still interested in the project, do let me know if you're facing any issues and I will be happy to try and help.
