### ISSUE TITLE
can't down ./download files

### ISSUE THREAD

**Issue by wuzhengxuan** [mosessoh/CNN-LSTM-Caption-Generator#8]
Hey, I tried downloading it, but I am getting the above mentioned 404 Error. Can you please reupload the model?

**Comment by wuzhengxuan** [comment]
Thanks very much

**Comment by fighting41love** [comment]
Thanks for sharing the code. The download.sh doesn't work.
Hope someone can upload the model.
Thanks!

**Comment by tkhunkhe** [comment]
Same, Can you please reupload the model? or redirect us to where we could download the model. Thanks.

**Comment by mosessoh** [comment]
Please see my response in #12 . I've created a new download.sh script that should fix the issues you're facing. You should now be able to use the new download.sh script by cloning/pulling the repo. If you're still interested in the project, do let me know if you're facing any issues and I will be happy to try and help.
