### ISSUE TITLE
how to train?

### ISSUE THREAD

**Issue by 201528014227051** [mosessoh/CNN-LSTM-Caption-Generator#9]
thanks the author! and i wanna train new model , but don't know how to do it, could you please tell me or give a insutruction in the readme file?

**Comment by mosessoh** [comment]
I'm sorry but I do not have the time to detail exactly how training works. However, I think you'll find what you need in the `model.py` file. Most of the code in `main()` will help with training - I'm sure you can build on that base to train a new model.

I've also uploaded my trained models to a new S3 bucket (see #12) following multiple connectivity issues to my Google Drive folder. Those are a good start point for fine-tuning a new model. Hope these help!
